version: "3"

services:
    'fusspflegeplus':
        build:
            context: .
            dockerfile: Dockerfile
        container_name: 'fusspflegeplus.ch'
        image: christiangroeber/fusspflegeplus
        ports:
            - '94:80'
        volumes: 
            - ./:/var/www/html